source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'WMCategoryKit_Example' do
  pod 'WMCategoryKit', :path => '../'

  target 'WMCategoryKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
